<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil"><HintPath>../lib/Mono.Cecil.dll</HintPath></Reference>
    <Reference Include="Mono.Cecil.Rocks"><HintPath>../lib/Mono.Cecil.Rocks.dll</HintPath></Reference>
  </ItemGroup>
</Project>
